# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvmat_bgr <- function(img, width = 0L, height = 0L) {
    .Call('_image_textlinedetector_cvmat_bgr', PACKAGE = 'image.textlinedetector', img, width, height)
}

cvmat_bw <- function(img, width = 0L, height = 0L) {
    .Call('_image_textlinedetector_cvmat_bw', PACKAGE = 'image.textlinedetector', img, width, height)
}

cvmat_rect <- function(ptr, x, y, width = 0L, height = 0L) {
    .Call('_image_textlinedetector_cvmat_rect', PACKAGE = 'image.textlinedetector', ptr, x, y, width, height)
}

cvmat_polygon <- function(ptr, pts, convex = FALSE, crop = FALSE, color = 255L) {
    .Call('_image_textlinedetector_cvmat_polygon', PACKAGE = 'image.textlinedetector', ptr, pts, convex, crop, color)
}

cvmat_bitmap <- function(ptr) {
    .Call('_image_textlinedetector_cvmat_bitmap', PACKAGE = 'image.textlinedetector', ptr)
}

cvmat_info <- function(image) {
    .Call('_image_textlinedetector_cvmat_info', PACKAGE = 'image.textlinedetector', image)
}

textlinedetector_astarpath <- function(ptr, morph = TRUE, step = 2L, mfactor = 5L, trace = TRUE) {
    .Call('_image_textlinedetector_textlinedetector_astarpath', PACKAGE = 'image.textlinedetector', ptr, morph, step, mfactor, trace)
}

textlinedetector_crop <- function(ptr) {
    .Call('_image_textlinedetector_textlinedetector_crop', PACKAGE = 'image.textlinedetector', ptr)
}

textlinedetector_resize <- function(ptr, width = 1280L) {
    .Call('_image_textlinedetector_textlinedetector_resize', PACKAGE = 'image.textlinedetector', ptr, width)
}

textlinedetector_binarization <- function(ptr, light = TRUE, type = 3L) {
    .Call('_image_textlinedetector_textlinedetector_binarization', PACKAGE = 'image.textlinedetector', ptr, light, type)
}

textlinedetector_linesegmentation <- function(ptr, chunksNumber = 8L, chunksProcess = 4L, kernelSize = 11L, sigma = 11L, theta = 7L) {
    .Call('_image_textlinedetector_textlinedetector_linesegmentation', PACKAGE = 'image.textlinedetector', ptr, chunksNumber, chunksProcess, kernelSize, sigma, theta)
}

textlinedetector_wordsegmentation <- function(ptr, kernelSize = 11L, sigma = 11L, theta = 7L) {
    .Call('_image_textlinedetector_textlinedetector_wordsegmentation', PACKAGE = 'image.textlinedetector', ptr, kernelSize, sigma, theta)
}

sieve <- function(original = TRUE) {
    .Call('_image_textlinedetector_sieve', PACKAGE = 'image.textlinedetector', original)
}

