# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvmat_bgr <- function(img, width = 0L, height = 0L) {
    .Call('_image_textlinedetector_cvmat_bgr', PACKAGE = 'image.textlinedetector', img, width, height)
}

cvmat_destroy <- function(image) {
    invisible(.Call('_image_textlinedetector_cvmat_destroy', PACKAGE = 'image.textlinedetector', image))
}

cvmat_dead <- function(image) {
    .Call('_image_textlinedetector_cvmat_dead', PACKAGE = 'image.textlinedetector', image)
}

cvmat_size <- function(image) {
    .Call('_image_textlinedetector_cvmat_size', PACKAGE = 'image.textlinedetector', image)
}

cvmat_new <- function() {
    .Call('_image_textlinedetector_cvmat_new', PACKAGE = 'image.textlinedetector')
}

cvmat_dupe <- function(image) {
    .Call('_image_textlinedetector_cvmat_dupe', PACKAGE = 'image.textlinedetector', image)
}

cvmat_read <- function(path) {
    .Call('_image_textlinedetector_cvmat_read', PACKAGE = 'image.textlinedetector', path)
}

cvmat_camera <- function() {
    .Call('_image_textlinedetector_cvmat_camera', PACKAGE = 'image.textlinedetector')
}

cvmat_write <- function(image, path) {
    .Call('_image_textlinedetector_cvmat_write', PACKAGE = 'image.textlinedetector', image, path)
}

cvmat_resize <- function(ptr, width = 0L, height = 0L) {
    .Call('_image_textlinedetector_cvmat_resize', PACKAGE = 'image.textlinedetector', ptr, width, height)
}

cvmat_bitmap <- function(ptr) {
    .Call('_image_textlinedetector_cvmat_bitmap', PACKAGE = 'image.textlinedetector', ptr)
}

cvmat_copyto <- function(from, to, mask) {
    .Call('_image_textlinedetector_cvmat_copyto', PACKAGE = 'image.textlinedetector', from, to, mask)
}

cvmat_info <- function(image) {
    .Call('_image_textlinedetector_cvmat_info', PACKAGE = 'image.textlinedetector', image)
}

cvmat_display <- function(ptr) {
    invisible(.Call('_image_textlinedetector_cvmat_display', PACKAGE = 'image.textlinedetector', ptr))
}

livestream <- function(filter) {
    invisible(.Call('_image_textlinedetector_livestream', PACKAGE = 'image.textlinedetector', filter))
}

data_prefix <- function() {
    .Call('_image_textlinedetector_data_prefix', PACKAGE = 'image.textlinedetector')
}

set_num_threads <- function(n = 0L) {
    .Call('_image_textlinedetector_set_num_threads', PACKAGE = 'image.textlinedetector', n)
}

#' @export
textlinedetector_crop <- function(ptr) {
    .Call('_image_textlinedetector_textlinedetector_crop', PACKAGE = 'image.textlinedetector', ptr)
}

#' @export
textlinedetector_resize <- function(ptr, newW = 1280L) {
    .Call('_image_textlinedetector_textlinedetector_resize', PACKAGE = 'image.textlinedetector', ptr, newW)
}

#' @export
textlinedetector_binarization <- function(ptr, light = TRUE, type = 3L) {
    .Call('_image_textlinedetector_textlinedetector_binarization', PACKAGE = 'image.textlinedetector', ptr, light, type)
}

#' @export
textlinedetector_linesegmentation <- function(ptr, chunksNumber = 8L, chunksProcess = 4L, kernelSize = 11L, sigma = 11L, theta = 7L) {
    .Call('_image_textlinedetector_textlinedetector_linesegmentation', PACKAGE = 'image.textlinedetector', ptr, chunksNumber, chunksProcess, kernelSize, sigma, theta)
}

#' @export
textlinedetector_wordsegmentation <- function(ptr, kernelSize = 11L, sigma = 11L, theta = 7L) {
    .Call('_image_textlinedetector_textlinedetector_wordsegmentation', PACKAGE = 'image.textlinedetector', ptr, kernelSize, sigma, theta)
}

